#!/bin/bash
set -o noclobber
printf '#include <stdio.h>\n\n/**\n * main - \n * @argc: number of arguments (argument count)\n * @argv: the values of arguments (argument values)\n * \n * Return: Always 0 on success\n */\n\n\n' > $1
set +o noclobber
vi $1
